import { DETAILS } from './details.js'

// Eras label periods for the scrubber readout and entry chips.
export const ERAS = [
  { id: 'pre', name: 'Axial Age', start: -650, end: -480 },
  { id: 'cla', name: 'Classical', start: -480, end: -300 },
  { id: 'hel', name: 'Classical Empires', start: -345, end: 200 },
  { id: 'med', name: 'Medieval', start: 200, end: 1400 },
  { id: 'ren', name: 'Renaissance & Early Modern', start: 1400, end: 1700 },
  { id: 'enl', name: 'Enlightenment', start: 1700, end: 1800 },
  { id: 'c19', name: '19th Century', start: 1795, end: 1905 },
  { id: 'c20', name: '20th Century', start: 1885, end: 2026 },
]

// v1 ships the Western canon; `tradition` and parallel timeline lanes are the
// extension point for Chinese / Indian / Islamic tracks in v2.
const WESTERN = [
  // ---- Pre-Socratic ----
  { id: 'thales', name: 'Thales', born: -624, died: -546, era: 'pre', school: 'Milesian',
    blurb: 'Asked what everything is made of — answered "water" — and in doing so swapped myth for natural explanation. Philosophy starts here.',
    line: 'What is everything made of?', influences: [] },
  { id: 'anaximander', name: 'Anaximander', born: -610, died: -546, era: 'pre', school: 'Milesian',
    blurb: 'Answered his teacher Thales with something stranger: the origin of all things is the apeiron, the boundless. Drew the first known map of the world and guessed that life began in the sea.',
    line: 'The origin of things is the boundless.', influences: ['thales'] },
  { id: 'pythagoras', name: 'Pythagoras', born: -570, died: -495, era: 'pre', school: 'Pythagorean',
    blurb: 'Found the cosmos ordered by number and proportion, fusing mathematics with mysticism and shaping Plato after him.',
    line: 'Reality is number.', influences: [] },
  { id: 'heraclitus', name: 'Heraclitus', born: -535, died: -475, era: 'pre', school: 'Ionian',
    blurb: 'Reality is ceaseless flux held together by an underlying logos; opposites define and depend on each other.',
    line: 'No one steps in the same river twice.', influences: [] },
  { id: 'parmenides', name: 'Parmenides', born: -515, died: -450, era: 'pre', school: 'Eleatic',
    blurb: 'Followed pure logic to a shocking place: change is impossible, being simply is, and the senses deceive us.',
    line: 'What is, is; what is not, is not.', influences: [] },

  // ---- Classical ----
  { id: 'socrates', name: 'Socrates', born: -470, died: -399, era: 'cla', school: '—',
    blurb: 'Wrote nothing and questioned everyone. Moved philosophy from the stars to the street: how ought one to live?',
    line: 'The unexamined life is not worth living.', influences: [] },
  { id: 'democritus', name: 'Democritus', born: -460, died: -370, era: 'cla', school: 'Atomist',
    blurb: 'Everything is atoms and void — a guess about the deep structure of matter that took 2,300 years to vindicate.',
    line: 'Atoms and void.', influences: [] },
  { id: 'plato', name: 'Plato', born: -428, died: -348, era: 'cla', school: 'Academy',
    blurb: 'Behind shifting appearances stand perfect, eternal Forms; the visible world is their shadow. Founded the Academy and framed nearly every question that followed.',
    line: 'The visible world is a shadow of the real one.', influences: ['socrates', 'parmenides', 'pythagoras'] },
  { id: 'diogenes', name: 'Diogenes', born: -412, died: -323, era: 'cla', school: 'Cynic',
    blurb: 'Lived in a jar, owned nothing, and mocked every convention to prove that virtue needs no possessions. Plato called him "Socrates gone mad." When asked where he was from, he coined a new word.',
    line: 'I am a citizen of the world.', influences: ['socrates'] },
  { id: 'aristotle', name: 'Aristotle', born: -384, died: -322, era: 'cla', school: 'Lyceum',
    blurb: 'Catalogued logic, biology, ethics, and politics. Virtue is a habit; knowledge begins with the senses, not a separate world of Forms.',
    line: 'All men by nature desire to know.', influences: ['plato'] },

  // ---- Hellenistic & Roman ----
  { id: 'pyrrho', name: 'Pyrrho', born: -360, died: -270, era: 'hel', school: 'Skeptic',
    blurb: 'Marched to India with Alexander and came back doubting everything: every argument meets an equal counter-argument, so suspend judgment — and tranquility follows.',
    line: 'Suspend judgment, and calm follows.', influences: ['democritus'] },
  { id: 'epicurus', name: 'Epicurus', born: -341, died: -270, era: 'hel', school: 'Epicurean',
    blurb: 'The good life is untroubled pleasure: friends, simplicity, and the end of fear — especially the fear of death.',
    line: 'Death is nothing to us.', influences: ['democritus'] },
  { id: 'zeno', name: 'Zeno of Citium', born: -334, died: -262, era: 'hel', school: 'Stoic',
    blurb: 'Founded Stoicism after studying with the Cynics: virtue alone suffices for happiness, and wisdom is living in agreement with nature.',
    line: 'Live according to nature.', influences: ['socrates', 'diogenes'] },
  { id: 'marcus', name: 'Marcus Aurelius', born: 121, died: 180, era: 'hel', school: 'Stoic',
    blurb: 'Roman emperor writing private exercises to himself on duty, impermanence, and keeping an even mind under pressure.',
    line: 'You have power over your mind, not outside events.', influences: ['zeno'] },

  // ---- Medieval ----
  { id: 'plotinus', name: 'Plotinus', born: 204, died: 270, era: 'med', school: 'Neoplatonism',
    blurb: 'All reality emanates from the One, like light from a source; the soul’s task is the journey back inward. The bridge over which Plato entered Christian thought.',
    line: 'The soul’s journey is the return to the One.', influences: ['plato'] },
  { id: 'augustine', name: 'Augustine', born: 354, died: 430, era: 'med', school: 'Christian Platonism',
    blurb: 'Turned Plato inward: truth is sought in the restless interior self before God. Defined the next thousand years of Western thought.',
    line: 'Our heart is restless until it rests in you.', influences: ['plato', 'plotinus'] },
  { id: 'anselm', name: 'Anselm', born: 1033, died: 1109, era: 'med', school: 'Scholasticism',
    blurb: 'Faith seeking understanding: reason can climb toward what faith already holds. His ontological argument — God as that than which nothing greater can be conceived — is still debated.',
    line: 'Faith seeking understanding.', influences: ['augustine'] },
  { id: 'aquinas', name: 'Thomas Aquinas', born: 1225, died: 1274, era: 'med', school: 'Scholasticism',
    blurb: 'Reconciled Aristotle with Christian doctrine — reason and faith as two roads to one truth — in vast, systematic order.',
    line: 'Reason and faith are two roads to one truth.', influences: ['aristotle', 'augustine', 'avicenna', 'averroes'] },
  { id: 'ockham', name: 'William of Ockham', born: 1287, died: 1347, era: 'med', school: 'Nominalism',
    blurb: 'Do not multiply entities beyond necessity — the razor that bears his name. Universals are labels, not things; the simplest adequate explanation wins.',
    line: 'The simplest explanation is best.', influences: ['aristotle'] },

  // ---- Renaissance & Early Modern ----
  { id: 'machiavelli', name: 'Machiavelli', born: 1469, died: 1527, era: 'ren', school: 'Political realism',
    blurb: 'Studied politics as it is, not as it ought to be. Power has its own logic, and pretending otherwise is how princes fall.',
    line: 'Study politics as it is, not as it ought to be.', influences: [] },
  { id: 'bacon', name: 'Francis Bacon', born: 1561, died: 1626, era: 'ren', school: 'Empirical method',
    blurb: 'Nature yields her secrets to organized experiment, not to inherited authority. Sketched the method that became modern science.',
    line: 'Knowledge is power.', influences: [] },
  { id: 'hobbes', name: 'Thomas Hobbes', born: 1588, died: 1679, era: 'ren', school: 'Social contract',
    blurb: 'Without a sovereign to fear, life collapses into a war of all against all — solitary, poor, nasty, brutish, and short. Order is manufactured, never natural.',
    line: 'Without order, life is nasty, brutish, and short.', influences: ['machiavelli'] },
  { id: 'descartes', name: 'Descartes', born: 1596, died: 1650, era: 'ren', school: 'Rationalism',
    blurb: 'Doubted everything until one certainty survived — the thinking self — then rebuilt knowledge from it, splitting mind from matter.',
    line: 'I think, therefore I am.', influences: [] },
  { id: 'spinoza', name: 'Spinoza', born: 1632, died: 1677, era: 'ren', school: 'Rationalism',
    blurb: 'God and Nature are one infinite substance; human freedom is understanding necessity rather than escaping it.',
    line: 'God, or Nature.', influences: ['descartes'] },
  { id: 'locke', name: 'John Locke', born: 1632, died: 1704, era: 'ren', school: 'Empiricism',
    blurb: 'The mind begins blank; knowledge comes from experience, and legitimate government from the consent of the governed.',
    line: 'The mind begins as a blank slate.', influences: ['descartes'] },
  { id: 'leibniz', name: 'Leibniz', born: 1646, died: 1716, era: 'ren', school: 'Rationalism',
    blurb: 'Reality is infinitely many mind-like monads, pre-harmonized by God; this is the best of all possible worlds. Co-invented calculus and asked the deepest question there is.',
    line: 'Why is there something rather than nothing?', influences: ['descartes', 'spinoza'] },

  // ---- Enlightenment ----
  { id: 'berkeley', name: 'George Berkeley', born: 1685, died: 1753, era: 'enl', school: 'Idealism',
    blurb: 'Pushed empiricism into idealism: matter existing outside all perception is incoherent. Things are ideas; to be is to be perceived.',
    line: 'To be is to be perceived.', influences: ['locke'] },
  { id: 'hume', name: 'David Hume', born: 1711, died: 1776, era: 'enl', school: 'Empiricism',
    blurb: 'Pushed empiricism to its limit: causation is habit, the self is a bundle, and no "ought" follows from an "is."',
    line: 'Reason is the slave of the passions.', influences: ['locke', 'berkeley'] },
  { id: 'rousseau', name: 'Rousseau', born: 1712, died: 1778, era: 'enl', school: 'Social contract',
    blurb: 'Civilization corrupts a naturally good creature; a legitimate society rests on the general will of its members.',
    line: 'Man is born free, and everywhere he is in chains.', influences: [] },
  { id: 'kant', name: 'Immanuel Kant', born: 1724, died: 1804, era: 'enl', school: 'German idealism',
    blurb: 'The mind actively structures experience; morality is acting only on maxims you could will as universal law. The hinge of modern philosophy.',
    line: 'Dare to know.', influences: ['hume', 'rousseau'] },
  { id: 'bentham', name: 'Jeremy Bentham', born: 1748, died: 1832, era: 'enl', school: 'Utilitarianism',
    blurb: 'Morality made arithmetic: right is whatever produces the greatest happiness for the greatest number. Also designed the panopticon — a prison watched from a single point.',
    line: 'The greatest happiness of the greatest number.', influences: ['hume'] },
  { id: 'wollstonecraft', name: 'Mary Wollstonecraft', born: 1759, died: 1797, era: 'enl', school: 'Feminism',
    blurb: 'Answered Rousseau: reason has no sex. Deny women education and you manufacture the very "weakness" you then cite against them.',
    line: 'Not power over men, but over themselves.', influences: ['rousseau'] },

  // ---- 19th Century ----
  { id: 'hegel', name: 'Hegel', born: 1770, died: 1831, era: 'c19', school: 'German idealism',
    blurb: 'History is spirit coming to know itself through conflict and resolution — a process with a direction, not a series of accidents.',
    line: 'History is spirit coming to know itself.', influences: ['kant'] },
  { id: 'schopenhauer', name: 'Schopenhauer', born: 1788, died: 1860, era: 'c19', school: 'Pessimism',
    blurb: 'Beneath appearances the world is blind, insatiable Will — which is why existence aches. Art and compassion offer brief exits. The first major Western thinker to draw on Indian philosophy.',
    line: 'The world is will.', influences: ['kant', 'plato', 'buddha'] },
  { id: 'mill', name: 'J. S. Mill', born: 1806, died: 1873, era: 'c19', school: 'Utilitarianism',
    blurb: 'Right actions maximize well-being, and the only freedom worth the name is pursuing our own good in our own way.',
    line: 'Over himself, the individual is sovereign.', influences: ['bentham'] },
  { id: 'kierkegaard', name: 'Kierkegaard', born: 1813, died: 1855, era: 'c19', school: 'Existentialism',
    blurb: 'Against every grand system: truth is subjective commitment, and faith is a leap no philosophy can make on your behalf.',
    line: 'Truth is subjectivity.', influences: ['hegel'] },
  { id: 'marx', name: 'Karl Marx', born: 1818, died: 1883, era: 'c19', school: 'Historical materialism',
    blurb: 'History moves by material class struggle, and philosophy’s job is not to interpret the world but to change it.',
    line: 'The point is to change it.', influences: ['hegel'] },
  { id: 'james', name: 'William James', born: 1842, died: 1910, era: 'c19', school: 'Pragmatism',
    blurb: 'Truth is what works: beliefs are instruments, judged by the difference they make in lived experience. Wrote the founding textbook of psychology along the way.',
    line: 'Truth is what works.', influences: ['mill'] },
  { id: 'nietzsche', name: 'Nietzsche', born: 1844, died: 1900, era: 'c19', school: '—',
    blurb: 'Diagnosed the death of God and the crisis of values it leaves behind; called for creating new values beyond good and evil.',
    line: 'God is dead.', influences: ['heraclitus', 'schopenhauer'] },

  // ---- 20th Century ----
  { id: 'russell', name: 'Bertrand Russell', born: 1872, died: 1970, era: 'c20', school: 'Analytic',
    blurb: 'Made logic philosophy’s scalpel: co-wrote Principia Mathematica to ground mathematics itself, then spent decades as a jailed pacifist and public conscience.',
    line: 'Logic is the essence of philosophy.', influences: ['leibniz', 'hume'] },
  { id: 'wittgenstein', name: 'Wittgenstein', born: 1889, died: 1951, era: 'c20', school: 'Analytic',
    blurb: 'The limits of my language mean the limits of my world; philosophy’s work is untangling the knots language ties in our thinking.',
    line: 'Whereof one cannot speak, thereof one must be silent.', influences: ['russell'] },
  { id: 'heidegger', name: 'Heidegger', born: 1889, died: 1976, era: 'c20', school: 'Phenomenology',
    blurb: 'The forgotten question is Being itself — not things, but that they are at all. We are thrown into time, defined by death, and mostly busy fleeing that fact.',
    line: 'The question is what it means to be.', influences: ['kierkegaard', 'nietzsche'] },
  { id: 'sartre', name: 'Sartre', born: 1905, died: 1980, era: 'c20', school: 'Existentialism',
    blurb: 'We are radically free and therefore radically responsible — condemned to choose who we become.',
    line: 'Existence precedes essence.', influences: ['kierkegaard', 'nietzsche', 'heidegger'] },
  { id: 'arendt', name: 'Hannah Arendt', born: 1906, died: 1975, era: 'c20', school: 'Political theory',
    blurb: 'Thought the unthinkable of her century: how totalitarianism works, and how ordinary careerism — not monstrousness — can administer atrocity. Freedom lives in acting together in public.',
    line: 'Evil can be banal.', influences: ['heidegger', 'augustine'] },
  { id: 'beauvoir', name: 'Simone de Beauvoir', born: 1908, died: 1986, era: 'c20', school: 'Existentialism · Feminism',
    blurb: 'Freedom is always situated. Womanhood is made, not born — the founding analysis of feminist philosophy.',
    line: 'One is not born, but rather becomes, a woman.', influences: ['sartre', 'hegel'] },
  { id: 'camus', name: 'Albert Camus', born: 1913, died: 1960, era: 'c20', school: 'Absurdism',
    blurb: 'The absurd is the gap between our demand for meaning and the universe’s silence. Neither suicide nor a leap of faith — revolt, and live anyway.',
    line: 'One must imagine Sisyphus happy.', influences: ['nietzsche', 'kierkegaard'] },
  { id: 'rawls', name: 'John Rawls', born: 1921, died: 2002, era: 'c20', school: 'Political liberalism',
    blurb: 'Justice is the set of rules you would choose behind a veil of ignorance, not knowing which place in society would be yours.',
    line: 'Justice is fairness chosen behind a veil of ignorance.', influences: ['kant', 'mill'] },
  { id: 'foucault', name: 'Michel Foucault', born: 1926, died: 1984, era: 'c20', school: 'Post-structuralism',
    blurb: 'Power doesn’t just forbid — it produces: norms, categories, and "truths" enforced through prisons, clinics, and schools. His histories show how the present became thinkable.',
    line: 'Power is everywhere.', influences: ['nietzsche', 'marx'] },
  { id: 'searle', name: 'John Searle', born: 1932, died: null, era: 'c20', school: 'Analytic',
    blurb: 'Words do not just describe — they act; and a computer shuffling symbols understands nothing. Speech acts and the Chinese Room made him analytic philosophy’s great provocateur of mind and language.',
    line: 'Syntax is not semantics.', influences: ['wittgenstein'] },
  { id: 'kripke', name: 'Saul Kripke', born: 1940, died: 2022, era: 'c20', school: 'Analytic',
    blurb: 'Names refer directly, necessity is real, and possible worlds can be reasoned about with precision — three lectures delivered without notes redrew the map of language and metaphysics.',
    line: 'Names are rigid designators.', influences: ['leibniz', 'russell', 'wittgenstein'] },

  // ---- Chinese tradition ----
  { id: 'confucius', name: 'Confucius', born: -551, died: -479, era: 'pre', school: 'Confucian', tradition: 'chinese',
    blurb: 'Ritual, reverence, and cultivated character hold a society together; government is moral example before it is law. The most influential teacher in human history.',
    line: 'Do not impose on others what you do not wish for yourself.', influences: [] },
  { id: 'laozi', name: 'Laozi', born: -571, died: -471, era: 'pre', school: 'Daoist', tradition: 'chinese',
    blurb: 'The Way that can be spoken is not the eternal Way: the world runs best when we stop forcing it — effortless action, water wearing down stone.',
    line: 'The Way that can be told is not the eternal Way.', influences: [] },
  { id: 'mozi', name: 'Mozi', born: -470, died: -391, era: 'cla', school: 'Mohist', tradition: 'chinese',
    blurb: 'Against Confucian family-first ethics: care for everyone impartially, judge every practice by its benefit to the people — utilitarianism two millennia early.',
    line: 'Care for all impartially.', influences: ['confucius'] },
  { id: 'mencius', name: 'Mencius', born: -372, died: -289, era: 'cla', school: 'Confucian', tradition: 'chinese',
    blurb: 'Human nature is good the way sprouts are green: anyone seeing a child fall toward a well feels alarm. Ethics is cultivating what is already in us.',
    line: 'Human nature is good, as water flows downhill.', influences: ['confucius', 'mozi'] },
  { id: 'zhuangzi', name: 'Zhuangzi', born: -369, died: -286, era: 'cla', school: 'Daoist', tradition: 'chinese',
    blurb: 'Philosophy’s great comedian: dreamed he was a butterfly and woke unsure which he was. Perspectives are partial, categories are nets — the sage sits loose to all of them.',
    line: 'Am I a man who dreamt of being a butterfly, or a butterfly dreaming I am a man?', influences: ['laozi'] },
  { id: 'xunzi', name: 'Xunzi', born: -310, died: -235, era: 'cla', school: 'Confucian', tradition: 'chinese',
    blurb: 'Against Mencius: human nature is crooked timber, and ritual is the steam-press that straightens it. Order is an achievement of artifice, not a gift of nature.',
    line: 'Human nature is crooked; ritual straightens it.', influences: ['confucius', 'mencius'] },
  { id: 'zhuxi', name: 'Zhu Xi', born: 1130, died: 1200, era: 'med', school: 'Neo-Confucian', tradition: 'chinese',
    blurb: 'Synthesized a millennium of Chinese thought into one system of principle (li) and vital stuff (qi) — the orthodoxy tested on every Chinese civil-service exam for six hundred years.',
    line: 'Investigate things to extend knowledge.', influences: ['confucius', 'mencius'] },
  { id: 'wangyangming', name: 'Wang Yangming', born: 1472, died: 1529, era: 'ren', school: 'Neo-Confucian', tradition: 'chinese',
    blurb: 'General, statesman, and sage who turned Zhu Xi inside out: principle is not in things but in the mind, and knowledge that does not act is not yet knowledge.',
    line: 'Knowledge and action are one.', influences: ['mencius', 'zhuxi'] },

  // ---- Indian tradition ----
  { id: 'buddha', name: 'The Buddha', born: -563, died: -483, era: 'pre', school: 'Buddhist', tradition: 'indian',
    blurb: 'A prince who walked out of his palace and diagnosed existence: suffering arises from craving, craving can end, and there is a path. No self, no permanence — and peace on the far side of that.',
    line: 'All conditioned things are impermanent.', influences: [] },
  { id: 'mahavira', name: 'Mahavira', born: -599, died: -527, era: 'pre', school: 'Jain', tradition: 'indian',
    blurb: 'The great reformer of Jainism: absolute nonviolence toward every living being, many-sidedness of truth, and liberation through ascetic discipline.',
    line: 'Non-violence is the highest duty.', influences: [] },
  { id: 'nagarjuna', name: 'Nagarjuna', born: 150, died: 250, era: 'hel', school: 'Madhyamaka Buddhist', tradition: 'indian',
    blurb: 'Buddhism’s greatest logician: nothing has independent essence — everything exists only in dependence, and even emptiness is empty. The middle way, argued with a scalpel.',
    line: 'Emptiness is dependent origination.', influences: ['buddha'] },
  { id: 'shankara', name: 'Adi Shankara', born: 788, died: 820, era: 'med', school: 'Advaita Vedānta', tradition: 'indian',
    blurb: 'In thirty-two years, walked the length of India arguing that only Brahman is real: the self and the absolute are one, and the world of difference is a magician’s show.',
    line: 'Brahman alone is real; the world is appearance.', influences: ['nagarjuna'] },
  { id: 'ramanuja', name: 'Ramanuja', born: 1017, died: 1137, era: 'med', school: 'Viśiṣṭādvaita', tradition: 'indian',
    blurb: 'Against Shankara’s stark non-dualism: the world and souls are real — the body of God — and the highest knowledge is loving devotion, not bare identity.',
    line: 'The world is the body of God.', influences: ['shankara'] },

  // ---- Islamic tradition ----
  { id: 'alkindi', name: 'Al-Kindi', born: 801, died: 873, era: 'med', school: 'Falsafa', tradition: 'islamic',
    blurb: '"The Philosopher of the Arabs": led the Baghdad translation movement that carried Greek thought into Arabic, arguing that truth is truth whatever its source.',
    line: 'We should not be ashamed to acknowledge truth from whatever source it comes.', influences: ['aristotle', 'plotinus'] },
  { id: 'alfarabi', name: 'Al-Farabi', born: 872, died: 950, era: 'med', school: 'Falsafa', tradition: 'islamic',
    blurb: 'The "Second Teacher" after Aristotle: fused Greek logic with Plato’s politics into the virtuous city, and made philosophy the deepest reading of religion.',
    line: 'The virtuous city is ordered like a healthy body.', influences: ['aristotle', 'plato', 'alkindi'] },
  { id: 'avicenna', name: 'Avicenna', born: 980, died: 1037, era: 'med', school: 'Falsafa', tradition: 'islamic',
    blurb: 'Physician-philosopher who systematized everything: essence versus existence, the Necessary Existent, the floating man who knows himself with no body at all. Europe learned its Aristotle through him.',
    line: 'Essence is distinct from existence.', influences: ['aristotle', 'alfarabi'] },
  { id: 'alghazali', name: 'Al-Ghazali', born: 1058, died: 1111, era: 'med', school: 'Sufi theology', tradition: 'islamic',
    blurb: 'At the peak of fame he broke down, left everything, and wandered as a Sufi. His Incoherence of the Philosophers turned philosophy’s own logic against its necessities — causation is God’s habit, not nature’s law.',
    line: 'Causation is the habit of God.', influences: ['avicenna'] },
  { id: 'averroes', name: 'Averroes', born: 1126, died: 1198, era: 'med', school: 'Falsafa', tradition: 'islamic',
    blurb: 'Córdoba’s judge and "The Commentator" on Aristotle: answered Al-Ghazali blow for blow, argued philosophy and revelation teach one truth, and lit the fire of European scholasticism.',
    line: 'Truth does not contradict truth.', influences: ['aristotle', 'avicenna', 'alghazali'] },
  { id: 'ibnkhaldun', name: 'Ibn Khaldun', born: 1332, died: 1406, era: 'ren', school: 'Historiography', tradition: 'islamic',
    blurb: 'Invented social science in a fortress in Algeria: dynasties rise on group solidarity (asabiyyah), soften in luxury, and fall in four generations — history as a system with laws.',
    line: 'Group solidarity raises dynasties; luxury unravels them.', influences: ['averroes'] },

  // ---- Jewish tradition ----
  { id: 'maimonides', name: 'Maimonides', born: 1138, died: 1204, era: 'med', school: 'Jewish rationalism', tradition: 'jewish',
    blurb: 'Córdoba-born physician to Saladin’s court and the greatest Jewish thinker of the Middle Ages: squared Torah with Aristotle, and taught that of God we can only say what He is not.',
    line: 'Of God, say only what He is not.', influences: ['aristotle', 'alfarabi'] },
]

// Birthplaces (approximate town coordinates) for the globe view.
const PLACES = {
  thales: { name: 'Miletus', lat: 37.53, lon: 27.28 },
  anaximander: { name: 'Miletus', lat: 37.53, lon: 27.28 },
  pythagoras: { name: 'Samos', lat: 37.75, lon: 26.83 },
  heraclitus: { name: 'Ephesus', lat: 37.95, lon: 27.37 },
  parmenides: { name: 'Elea', lat: 40.16, lon: 15.15 },
  socrates: { name: 'Athens', lat: 37.98, lon: 23.73 },
  democritus: { name: 'Abdera', lat: 40.94, lon: 24.98 },
  plato: { name: 'Athens', lat: 37.98, lon: 23.73 },
  diogenes: { name: 'Sinope', lat: 42.03, lon: 35.15 },
  aristotle: { name: 'Stagira', lat: 40.53, lon: 23.75 },
  pyrrho: { name: 'Elis', lat: 37.89, lon: 21.37 },
  epicurus: { name: 'Samos', lat: 37.75, lon: 26.83 },
  zeno: { name: 'Citium', lat: 34.92, lon: 33.63 },
  marcus: { name: 'Rome', lat: 41.89, lon: 12.48 },
  plotinus: { name: 'Lycopolis', lat: 27.18, lon: 31.18 },
  augustine: { name: 'Thagaste', lat: 36.29, lon: 7.95 },
  anselm: { name: 'Aosta', lat: 45.74, lon: 7.32 },
  aquinas: { name: 'Roccasecca', lat: 41.55, lon: 13.67 },
  ockham: { name: 'Ockham, Surrey', lat: 51.3, lon: -0.45 },
  machiavelli: { name: 'Florence', lat: 43.77, lon: 11.25 },
  bacon: { name: 'London', lat: 51.51, lon: -0.13 },
  hobbes: { name: 'Malmesbury', lat: 51.58, lon: -2.1 },
  descartes: { name: 'La Haye, Touraine', lat: 46.99, lon: 0.7 },
  spinoza: { name: 'Amsterdam', lat: 52.37, lon: 4.9 },
  locke: { name: 'Wrington', lat: 51.36, lon: -2.76 },
  leibniz: { name: 'Leipzig', lat: 51.34, lon: 12.37 },
  berkeley: { name: 'Kilkenny', lat: 52.65, lon: -7.25 },
  hume: { name: 'Edinburgh', lat: 55.95, lon: -3.19 },
  rousseau: { name: 'Geneva', lat: 46.2, lon: 6.14 },
  kant: { name: 'Königsberg', lat: 54.71, lon: 20.51 },
  bentham: { name: 'London', lat: 51.51, lon: -0.13 },
  wollstonecraft: { name: 'London', lat: 51.52, lon: -0.07 },
  hegel: { name: 'Stuttgart', lat: 48.78, lon: 9.18 },
  schopenhauer: { name: 'Danzig', lat: 54.35, lon: 18.65 },
  mill: { name: 'London', lat: 51.53, lon: -0.11 },
  kierkegaard: { name: 'Copenhagen', lat: 55.68, lon: 12.57 },
  marx: { name: 'Trier', lat: 49.75, lon: 6.64 },
  james: { name: 'New York', lat: 40.71, lon: -74.01 },
  nietzsche: { name: 'Röcken', lat: 51.25, lon: 12.11 },
  russell: { name: 'Trellech, Wales', lat: 51.74, lon: -2.73 },
  wittgenstein: { name: 'Vienna', lat: 48.21, lon: 16.37 },
  heidegger: { name: 'Messkirch', lat: 47.99, lon: 9.11 },
  sartre: { name: 'Paris', lat: 48.86, lon: 2.35 },
  arendt: { name: 'Hanover', lat: 52.37, lon: 9.72 },
  beauvoir: { name: 'Paris', lat: 48.86, lon: 2.35 },
  camus: { name: 'Mondovi, Algeria', lat: 36.68, lon: 7.75 },
  rawls: { name: 'Baltimore', lat: 39.29, lon: -76.61 },
  foucault: { name: 'Poitiers', lat: 46.58, lon: 0.34 },
  searle: { name: 'Denver', lat: 39.74, lon: -104.99 },
  kripke: { name: 'Bay Shore, New York', lat: 40.72, lon: -73.25 },
  confucius: { name: 'Qufu', lat: 35.6, lon: 116.98 },
  laozi: { name: 'Luyi', lat: 33.86, lon: 115.48 },
  mozi: { name: 'Tengzhou', lat: 35.08, lon: 117.17 },
  mencius: { name: 'Zoucheng', lat: 35.4, lon: 117.0 },
  zhuangzi: { name: 'Shangqiu', lat: 34.45, lon: 115.65 },
  xunzi: { name: 'Handan', lat: 36.6, lon: 114.5 },
  zhuxi: { name: 'Youxi, Fujian', lat: 26.17, lon: 118.19 },
  wangyangming: { name: 'Yuyao', lat: 30.04, lon: 121.15 },
  buddha: { name: 'Lumbini', lat: 27.47, lon: 83.28 },
  mahavira: { name: 'Kundagrama, near Vaishali', lat: 25.99, lon: 85.13 },
  nagarjuna: { name: 'Amaravati region', lat: 16.57, lon: 80.36 },
  shankara: { name: 'Kaladi, Kerala', lat: 10.17, lon: 76.44 },
  ramanuja: { name: 'Sriperumbudur', lat: 12.97, lon: 79.95 },
  alkindi: { name: 'Kufa', lat: 32.03, lon: 44.4 },
  alfarabi: { name: 'Farab (Otrar)', lat: 42.85, lon: 68.3 },
  avicenna: { name: 'Afshana, near Bukhara', lat: 39.77, lon: 64.55 },
  alghazali: { name: 'Tus', lat: 36.5, lon: 59.57 },
  averroes: { name: 'Córdoba', lat: 37.88, lon: -4.78 },
  ibnkhaldun: { name: 'Tunis', lat: 36.8, lon: 10.18 },
  maimonides: { name: 'Córdoba', lat: 37.88, lon: -4.78 },
}

// Further-reading targets: Stanford Encyclopedia entry slug, Wikipedia title,
// and whether meaningful public-domain texts exist on Project Gutenberg.
const LINKS = {
  thales: { sep: 'presocratics', wiki: 'Thales', pd: true },
  anaximander: { sep: 'presocratics', wiki: 'Anaximander', pd: true },
  pythagoras: { sep: 'pythagoras', wiki: 'Pythagoras', pd: true },
  heraclitus: { sep: 'heraclitus', wiki: 'Heraclitus', pd: true },
  parmenides: { sep: 'parmenides', wiki: 'Parmenides', pd: true },
  socrates: { sep: 'socrates', wiki: 'Socrates', pd: true },
  democritus: { sep: 'democritus', wiki: 'Democritus', pd: true },
  plato: { sep: 'plato', wiki: 'Plato', pd: true },
  diogenes: { sep: 'diogenes-sinope', wiki: 'Diogenes', pd: true },
  aristotle: { sep: 'aristotle', wiki: 'Aristotle', pd: true },
  pyrrho: { sep: 'pyrrho', wiki: 'Pyrrho', pd: true },
  epicurus: { sep: 'epicurus', wiki: 'Epicurus', pd: true },
  zeno: { sep: 'zeno-citium', wiki: 'Zeno_of_Citium', pd: true },
  marcus: { sep: 'marcus-aurelius', wiki: 'Marcus_Aurelius', pd: true },
  plotinus: { sep: 'plotinus', wiki: 'Plotinus', pd: true },
  augustine: { sep: 'augustine', wiki: 'Augustine_of_Hippo', pd: true },
  anselm: { sep: 'anselm', wiki: 'Anselm_of_Canterbury', pd: true },
  aquinas: { sep: 'aquinas', wiki: 'Thomas_Aquinas', pd: true },
  ockham: { sep: 'ockham', wiki: 'William_of_Ockham', pd: true },
  machiavelli: { sep: 'machiavelli', wiki: 'Niccolo_Machiavelli', pd: true },
  bacon: { sep: 'francis-bacon', wiki: 'Francis_Bacon', pd: true },
  hobbes: { sep: 'hobbes', wiki: 'Thomas_Hobbes', pd: true },
  descartes: { sep: 'descartes', wiki: 'Rene_Descartes', pd: true },
  spinoza: { sep: 'spinoza', wiki: 'Baruch_Spinoza', pd: true },
  locke: { sep: 'locke', wiki: 'John_Locke', pd: true },
  leibniz: { sep: 'leibniz', wiki: 'Gottfried_Wilhelm_Leibniz', pd: true },
  berkeley: { sep: 'berkeley', wiki: 'George_Berkeley', pd: true },
  hume: { sep: 'hume', wiki: 'David_Hume', pd: true },
  rousseau: { sep: 'rousseau', wiki: 'Jean-Jacques_Rousseau', pd: true },
  kant: { sep: 'kant', wiki: 'Immanuel_Kant', pd: true },
  bentham: { sep: 'bentham', wiki: 'Jeremy_Bentham', pd: true },
  wollstonecraft: { sep: 'wollstonecraft', wiki: 'Mary_Wollstonecraft', pd: true },
  hegel: { sep: 'hegel', wiki: 'Georg_Wilhelm_Friedrich_Hegel', pd: true },
  schopenhauer: { sep: 'schopenhauer', wiki: 'Arthur_Schopenhauer', pd: true },
  mill: { sep: 'mill', wiki: 'John_Stuart_Mill', pd: true },
  kierkegaard: { sep: 'kierkegaard', wiki: 'Soren_Kierkegaard', pd: true },
  marx: { sep: 'marx', wiki: 'Karl_Marx', pd: true },
  james: { sep: 'james', wiki: 'William_James', pd: true },
  nietzsche: { sep: 'nietzsche', wiki: 'Friedrich_Nietzsche', pd: true },
  russell: { sep: 'russell', wiki: 'Bertrand_Russell', pd: true },
  wittgenstein: { sep: 'wittgenstein', wiki: 'Ludwig_Wittgenstein', pd: true },
  heidegger: { sep: 'heidegger', wiki: 'Martin_Heidegger', pd: false },
  sartre: { sep: 'sartre', wiki: 'Jean-Paul_Sartre', pd: false },
  arendt: { sep: 'arendt', wiki: 'Hannah_Arendt', pd: false },
  beauvoir: { sep: 'beauvoir', wiki: 'Simone_de_Beauvoir', pd: false },
  camus: { sep: 'camus', wiki: 'Albert_Camus', pd: false },
  rawls: { sep: 'rawls', wiki: 'John_Rawls', pd: false },
  foucault: { sep: 'foucault', wiki: 'Michel_Foucault', pd: false },
  searle: { sep: 'chinese-room', wiki: 'John_Searle', pd: false },
  kripke: { sep: 'rigid-designators', wiki: 'Saul_Kripke', pd: false },
  confucius: { sep: 'confucius', wiki: 'Confucius', pd: true },
  laozi: { sep: 'laozi', wiki: 'Laozi', pd: true },
  mozi: { sep: 'mohism', wiki: 'Mozi', pd: true },
  mencius: { sep: 'mencius', wiki: 'Mencius', pd: true },
  zhuangzi: { sep: 'zhuangzi', wiki: 'Zhuangzi', pd: true },
  xunzi: { sep: 'xunzi', wiki: 'Xunzi_(philosopher)', pd: true },
  zhuxi: { sep: 'zhu-xi', wiki: 'Zhu_Xi', pd: false },
  wangyangming: { sep: 'wang-yangming', wiki: 'Wang_Yangming', pd: false },
  buddha: { sep: 'buddha', wiki: 'The_Buddha', pd: true },
  mahavira: { sep: 'jaina-philosophy', wiki: 'Mahavira', pd: false },
  nagarjuna: { sep: 'nagarjuna', wiki: 'Nagarjuna', pd: false },
  shankara: { sep: 'shankara', wiki: 'Adi_Shankara', pd: false },
  ramanuja: { sep: null, iep: 'ramanuja', wiki: 'Ramanuja', pd: false },
  alkindi: { sep: 'al-kindi', wiki: 'Al-Kindi', pd: false },
  alfarabi: { sep: 'al-farabi', wiki: 'Al-Farabi', pd: false },
  avicenna: { sep: 'ibn-sina', wiki: 'Avicenna', pd: false },
  alghazali: { sep: 'al-ghazali', wiki: 'Al-Ghazali', pd: true },
  averroes: { sep: 'ibn-rushd', wiki: 'Averroes', pd: false },
  ibnkhaldun: { sep: null, wiki: 'Ibn_Khaldun', pd: false },
  maimonides: { sep: 'maimonides', wiki: 'Maimonides', pd: true },
}

export const PHILOSOPHERS = WESTERN.map(p => ({
  ...p,
  ...DETAILS[p.id],
  tradition: p.tradition ?? 'western',
  portrait: `portraits/${p.id}.jpg`,
  thumb: `portraits/thumbs/${p.id}.png`,
  place: PLACES[p.id],
  alias: LINKS[p.id].wiki.replaceAll('_', ' '),
  influenced: WESTERN.filter(q => q.influences.includes(p.id)).map(q => q.id),
  links: [
    ...(LINKS[p.id].sep
      ? [{ label: 'Stanford Encyclopedia', url: `https://plato.stanford.edu/entries/${LINKS[p.id].sep}/` }]
      : []),
    ...(LINKS[p.id].iep
      ? [{ label: 'Internet Encyclopedia', url: `https://iep.utm.edu/${LINKS[p.id].iep}/` }]
      : []),
    { label: 'Wikipedia', url: `https://en.wikipedia.org/wiki/${LINKS[p.id].wiki}` },
    ...(LINKS[p.id].pd
      ? [{
          label: 'Texts on Gutenberg',
          url: `https://www.gutenberg.org/ebooks/search/?query=${encodeURIComponent(LINKS[p.id].wiki.replaceAll('_', ' '))}`,
        }]
      : []),
  ],
}))

export const byId = Object.fromEntries(PHILOSOPHERS.map(p => [p.id, p]))
export const eraById = Object.fromEntries(ERAS.map(e => [e.id, e]))
