import { DETAILS } from './details.js'

// Eras label periods for the scrubber readout and entry chips.
export const ERAS = [
  { id: 'pre', name: 'Pre-Socratic', start: -650, end: -480 },
  { id: 'cla', name: 'Classical', start: -480, end: -300 },
  { id: 'hel', name: 'Hellenistic & Roman', start: -345, end: 200 },
  { id: 'med', name: 'Medieval', start: 200, end: 1400 },
  { id: 'ren', name: 'Renaissance & Early Modern', start: 1400, end: 1700 },
  { id: 'enl', name: 'Enlightenment', start: 1700, end: 1800 },
  { id: 'c19', name: '19th Century', start: 1795, end: 1905 },
  { id: 'c20', name: '20th Century', start: 1885, end: 2015 },
]

// v1 ships the Western canon; `tradition` and parallel timeline lanes are the
// extension point for Chinese / Indian / Islamic tracks in v2.
const WESTERN = [
  // ---- Pre-Socratic ----
  { id: 'thales', name: 'Thales', born: -624, died: -546, era: 'pre', school: 'Milesian',
    blurb: 'Asked what everything is made of — answered "water" — and in doing so swapped myth for natural explanation. Philosophy starts here.',
    line: 'What is everything made of?', influences: [] },
  { id: 'anaximander', name: 'Anaximander', born: -610, died: -546, era: 'pre', school: 'Milesian',
    blurb: 'Answered his teacher Thales with something stranger: the origin of all things is the apeiron, the boundless. Drew the first known map of the world and guessed that life began in the sea.',
    line: 'The origin of things is the boundless.', influences: ['thales'] },
  { id: 'pythagoras', name: 'Pythagoras', born: -570, died: -495, era: 'pre', school: 'Pythagorean',
    blurb: 'Found the cosmos ordered by number and proportion, fusing mathematics with mysticism and shaping Plato after him.',
    line: 'Reality is number.', influences: [] },
  { id: 'heraclitus', name: 'Heraclitus', born: -535, died: -475, era: 'pre', school: 'Ionian',
    blurb: 'Reality is ceaseless flux held together by an underlying logos; opposites define and depend on each other.',
    line: 'No one steps in the same river twice.', influences: [] },
  { id: 'parmenides', name: 'Parmenides', born: -515, died: -450, era: 'pre', school: 'Eleatic',
    blurb: 'Followed pure logic to a shocking place: change is impossible, being simply is, and the senses deceive us.',
    line: 'What is, is; what is not, is not.', influences: [] },

  // ---- Classical ----
  { id: 'socrates', name: 'Socrates', born: -470, died: -399, era: 'cla', school: '—',
    blurb: 'Wrote nothing and questioned everyone. Moved philosophy from the stars to the street: how ought one to live?',
    line: 'The unexamined life is not worth living.', influences: [] },
  { id: 'democritus', name: 'Democritus', born: -460, died: -370, era: 'cla', school: 'Atomist',
    blurb: 'Everything is atoms and void — a guess about the deep structure of matter that took 2,300 years to vindicate.',
    line: 'Atoms and void.', influences: [] },
  { id: 'plato', name: 'Plato', born: -428, died: -348, era: 'cla', school: 'Academy',
    blurb: 'Behind shifting appearances stand perfect, eternal Forms; the visible world is their shadow. Founded the Academy and framed nearly every question that followed.',
    line: 'The visible world is a shadow of the real one.', influences: ['socrates', 'parmenides', 'pythagoras'] },
  { id: 'diogenes', name: 'Diogenes', born: -412, died: -323, era: 'cla', school: 'Cynic',
    blurb: 'Lived in a jar, owned nothing, and mocked every convention to prove that virtue needs no possessions. Plato called him "Socrates gone mad." When asked where he was from, he coined a new word.',
    line: 'I am a citizen of the world.', influences: ['socrates'] },
  { id: 'aristotle', name: 'Aristotle', born: -384, died: -322, era: 'cla', school: 'Lyceum',
    blurb: 'Catalogued logic, biology, ethics, and politics. Virtue is a habit; knowledge begins with the senses, not a separate world of Forms.',
    line: 'All men by nature desire to know.', influences: ['plato'] },

  // ---- Hellenistic & Roman ----
  { id: 'pyrrho', name: 'Pyrrho', born: -360, died: -270, era: 'hel', school: 'Skeptic',
    blurb: 'Marched to India with Alexander and came back doubting everything: every argument meets an equal counter-argument, so suspend judgment — and tranquility follows.',
    line: 'Suspend judgment, and calm follows.', influences: ['democritus'] },
  { id: 'epicurus', name: 'Epicurus', born: -341, died: -270, era: 'hel', school: 'Epicurean',
    blurb: 'The good life is untroubled pleasure: friends, simplicity, and the end of fear — especially the fear of death.',
    line: 'Death is nothing to us.', influences: ['democritus'] },
  { id: 'zeno', name: 'Zeno of Citium', born: -334, died: -262, era: 'hel', school: 'Stoic',
    blurb: 'Founded Stoicism after studying with the Cynics: virtue alone suffices for happiness, and wisdom is living in agreement with nature.',
    line: 'Live according to nature.', influences: ['socrates', 'diogenes'] },
  { id: 'marcus', name: 'Marcus Aurelius', born: 121, died: 180, era: 'hel', school: 'Stoic',
    blurb: 'Roman emperor writing private exercises to himself on duty, impermanence, and keeping an even mind under pressure.',
    line: 'You have power over your mind, not outside events.', influences: ['zeno'] },

  // ---- Medieval ----
  { id: 'plotinus', name: 'Plotinus', born: 204, died: 270, era: 'med', school: 'Neoplatonism',
    blurb: 'All reality emanates from the One, like light from a source; the soul’s task is the journey back inward. The bridge over which Plato entered Christian thought.',
    line: 'The soul’s journey is the return to the One.', influences: ['plato'] },
  { id: 'augustine', name: 'Augustine', born: 354, died: 430, era: 'med', school: 'Christian Platonism',
    blurb: 'Turned Plato inward: truth is sought in the restless interior self before God. Defined the next thousand years of Western thought.',
    line: 'Our heart is restless until it rests in you.', influences: ['plato', 'plotinus'] },
  { id: 'anselm', name: 'Anselm', born: 1033, died: 1109, era: 'med', school: 'Scholasticism',
    blurb: 'Faith seeking understanding: reason can climb toward what faith already holds. His ontological argument — God as that than which nothing greater can be conceived — is still debated.',
    line: 'Faith seeking understanding.', influences: ['augustine'] },
  { id: 'aquinas', name: 'Thomas Aquinas', born: 1225, died: 1274, era: 'med', school: 'Scholasticism',
    blurb: 'Reconciled Aristotle with Christian doctrine — reason and faith as two roads to one truth — in vast, systematic order.',
    line: 'Reason and faith are two roads to one truth.', influences: ['aristotle', 'augustine'] },
  { id: 'ockham', name: 'William of Ockham', born: 1287, died: 1347, era: 'med', school: 'Nominalism',
    blurb: 'Do not multiply entities beyond necessity — the razor that bears his name. Universals are labels, not things; the simplest adequate explanation wins.',
    line: 'The simplest explanation is best.', influences: ['aristotle'] },

  // ---- Renaissance & Early Modern ----
  { id: 'machiavelli', name: 'Machiavelli', born: 1469, died: 1527, era: 'ren', school: 'Political realism',
    blurb: 'Studied politics as it is, not as it ought to be. Power has its own logic, and pretending otherwise is how princes fall.',
    line: 'Study politics as it is, not as it ought to be.', influences: [] },
  { id: 'bacon', name: 'Francis Bacon', born: 1561, died: 1626, era: 'ren', school: 'Empirical method',
    blurb: 'Nature yields her secrets to organized experiment, not to inherited authority. Sketched the method that became modern science.',
    line: 'Knowledge is power.', influences: [] },
  { id: 'hobbes', name: 'Thomas Hobbes', born: 1588, died: 1679, era: 'ren', school: 'Social contract',
    blurb: 'Without a sovereign to fear, life collapses into a war of all against all — solitary, poor, nasty, brutish, and short. Order is manufactured, never natural.',
    line: 'Without order, life is nasty, brutish, and short.', influences: ['machiavelli'] },
  { id: 'descartes', name: 'Descartes', born: 1596, died: 1650, era: 'ren', school: 'Rationalism',
    blurb: 'Doubted everything until one certainty survived — the thinking self — then rebuilt knowledge from it, splitting mind from matter.',
    line: 'I think, therefore I am.', influences: [] },
  { id: 'spinoza', name: 'Spinoza', born: 1632, died: 1677, era: 'ren', school: 'Rationalism',
    blurb: 'God and Nature are one infinite substance; human freedom is understanding necessity rather than escaping it.',
    line: 'God, or Nature.', influences: ['descartes'] },
  { id: 'locke', name: 'John Locke', born: 1632, died: 1704, era: 'ren', school: 'Empiricism',
    blurb: 'The mind begins blank; knowledge comes from experience, and legitimate government from the consent of the governed.',
    line: 'The mind begins as a blank slate.', influences: ['descartes'] },
  { id: 'leibniz', name: 'Leibniz', born: 1646, died: 1716, era: 'ren', school: 'Rationalism',
    blurb: 'Reality is infinitely many mind-like monads, pre-harmonized by God; this is the best of all possible worlds. Co-invented calculus and asked the deepest question there is.',
    line: 'Why is there something rather than nothing?', influences: ['descartes', 'spinoza'] },

  // ---- Enlightenment ----
  { id: 'berkeley', name: 'George Berkeley', born: 1685, died: 1753, era: 'enl', school: 'Idealism',
    blurb: 'Pushed empiricism into idealism: matter existing outside all perception is incoherent. Things are ideas; to be is to be perceived.',
    line: 'To be is to be perceived.', influences: ['locke'] },
  { id: 'hume', name: 'David Hume', born: 1711, died: 1776, era: 'enl', school: 'Empiricism',
    blurb: 'Pushed empiricism to its limit: causation is habit, the self is a bundle, and no "ought" follows from an "is."',
    line: 'Reason is the slave of the passions.', influences: ['locke', 'berkeley'] },
  { id: 'rousseau', name: 'Rousseau', born: 1712, died: 1778, era: 'enl', school: 'Social contract',
    blurb: 'Civilization corrupts a naturally good creature; a legitimate society rests on the general will of its members.',
    line: 'Man is born free, and everywhere he is in chains.', influences: [] },
  { id: 'kant', name: 'Immanuel Kant', born: 1724, died: 1804, era: 'enl', school: 'German idealism',
    blurb: 'The mind actively structures experience; morality is acting only on maxims you could will as universal law. The hinge of modern philosophy.',
    line: 'Dare to know.', influences: ['hume', 'rousseau'] },
  { id: 'bentham', name: 'Jeremy Bentham', born: 1748, died: 1832, era: 'enl', school: 'Utilitarianism',
    blurb: 'Morality made arithmetic: right is whatever produces the greatest happiness for the greatest number. Also designed the panopticon — a prison watched from a single point.',
    line: 'The greatest happiness of the greatest number.', influences: ['hume'] },
  { id: 'wollstonecraft', name: 'Mary Wollstonecraft', born: 1759, died: 1797, era: 'enl', school: 'Feminism',
    blurb: 'Answered Rousseau: reason has no sex. Deny women education and you manufacture the very "weakness" you then cite against them.',
    line: 'Not power over men, but over themselves.', influences: ['rousseau'] },

  // ---- 19th Century ----
  { id: 'hegel', name: 'Hegel', born: 1770, died: 1831, era: 'c19', school: 'German idealism',
    blurb: 'History is spirit coming to know itself through conflict and resolution — a process with a direction, not a series of accidents.',
    line: 'History is spirit coming to know itself.', influences: ['kant'] },
  { id: 'schopenhauer', name: 'Schopenhauer', born: 1788, died: 1860, era: 'c19', school: 'Pessimism',
    blurb: 'Beneath appearances the world is blind, insatiable Will — which is why existence aches. Art and compassion offer brief exits. The first major Western thinker to draw on Indian philosophy.',
    line: 'The world is will.', influences: ['kant', 'plato'] },
  { id: 'mill', name: 'J. S. Mill', born: 1806, died: 1873, era: 'c19', school: 'Utilitarianism',
    blurb: 'Right actions maximize well-being, and the only freedom worth the name is pursuing our own good in our own way.',
    line: 'Over himself, the individual is sovereign.', influences: ['bentham'] },
  { id: 'kierkegaard', name: 'Kierkegaard', born: 1813, died: 1855, era: 'c19', school: 'Existentialism',
    blurb: 'Against every grand system: truth is subjective commitment, and faith is a leap no philosophy can make on your behalf.',
    line: 'Truth is subjectivity.', influences: ['hegel'] },
  { id: 'marx', name: 'Karl Marx', born: 1818, died: 1883, era: 'c19', school: 'Historical materialism',
    blurb: 'History moves by material class struggle, and philosophy’s job is not to interpret the world but to change it.',
    line: 'The point is to change it.', influences: ['hegel'] },
  { id: 'james', name: 'William James', born: 1842, died: 1910, era: 'c19', school: 'Pragmatism',
    blurb: 'Truth is what works: beliefs are instruments, judged by the difference they make in lived experience. Wrote the founding textbook of psychology along the way.',
    line: 'Truth is what works.', influences: ['mill'] },
  { id: 'nietzsche', name: 'Nietzsche', born: 1844, died: 1900, era: 'c19', school: '—',
    blurb: 'Diagnosed the death of God and the crisis of values it leaves behind; called for creating new values beyond good and evil.',
    line: 'God is dead.', influences: ['heraclitus', 'schopenhauer'] },

  // ---- 20th Century ----
  { id: 'russell', name: 'Bertrand Russell', born: 1872, died: 1970, era: 'c20', school: 'Analytic',
    blurb: 'Made logic philosophy’s scalpel: co-wrote Principia Mathematica to ground mathematics itself, then spent decades as a jailed pacifist and public conscience.',
    line: 'Logic is the essence of philosophy.', influences: ['leibniz', 'hume'] },
  { id: 'wittgenstein', name: 'Wittgenstein', born: 1889, died: 1951, era: 'c20', school: 'Analytic',
    blurb: 'The limits of my language mean the limits of my world; philosophy’s work is untangling the knots language ties in our thinking.',
    line: 'Whereof one cannot speak, thereof one must be silent.', influences: ['russell'] },
  { id: 'heidegger', name: 'Heidegger', born: 1889, died: 1976, era: 'c20', school: 'Phenomenology',
    blurb: 'The forgotten question is Being itself — not things, but that they are at all. We are thrown into time, defined by death, and mostly busy fleeing that fact.',
    line: 'The question is what it means to be.', influences: ['kierkegaard', 'nietzsche'] },
  { id: 'sartre', name: 'Sartre', born: 1905, died: 1980, era: 'c20', school: 'Existentialism',
    blurb: 'We are radically free and therefore radically responsible — condemned to choose who we become.',
    line: 'Existence precedes essence.', influences: ['kierkegaard', 'nietzsche', 'heidegger'] },
  { id: 'arendt', name: 'Hannah Arendt', born: 1906, died: 1975, era: 'c20', school: 'Political theory',
    blurb: 'Thought the unthinkable of her century: how totalitarianism works, and how ordinary careerism — not monstrousness — can administer atrocity. Freedom lives in acting together in public.',
    line: 'Evil can be banal.', influences: ['heidegger', 'augustine'] },
  { id: 'beauvoir', name: 'Simone de Beauvoir', born: 1908, died: 1986, era: 'c20', school: 'Existentialism · Feminism',
    blurb: 'Freedom is always situated. Womanhood is made, not born — the founding analysis of feminist philosophy.',
    line: 'One is not born, but rather becomes, a woman.', influences: ['sartre', 'hegel'] },
  { id: 'camus', name: 'Albert Camus', born: 1913, died: 1960, era: 'c20', school: 'Absurdism',
    blurb: 'The absurd is the gap between our demand for meaning and the universe’s silence. Neither suicide nor a leap of faith — revolt, and live anyway.',
    line: 'One must imagine Sisyphus happy.', influences: ['nietzsche', 'kierkegaard'] },
  { id: 'rawls', name: 'John Rawls', born: 1921, died: 2002, era: 'c20', school: 'Political liberalism',
    blurb: 'Justice is the set of rules you would choose behind a veil of ignorance, not knowing which place in society would be yours.',
    line: 'Justice is fairness chosen behind a veil of ignorance.', influences: ['kant', 'mill'] },
  { id: 'foucault', name: 'Michel Foucault', born: 1926, died: 1984, era: 'c20', school: 'Post-structuralism',
    blurb: 'Power doesn’t just forbid — it produces: norms, categories, and "truths" enforced through prisons, clinics, and schools. His histories show how the present became thinkable.',
    line: 'Power is everywhere.', influences: ['nietzsche', 'marx'] },
]

// Birthplaces (approximate town coordinates) for the globe view.
const PLACES = {
  thales: { name: 'Miletus', lat: 37.53, lon: 27.28 },
  anaximander: { name: 'Miletus', lat: 37.53, lon: 27.28 },
  pythagoras: { name: 'Samos', lat: 37.75, lon: 26.83 },
  heraclitus: { name: 'Ephesus', lat: 37.95, lon: 27.37 },
  parmenides: { name: 'Elea', lat: 40.16, lon: 15.15 },
  socrates: { name: 'Athens', lat: 37.98, lon: 23.73 },
  democritus: { name: 'Abdera', lat: 40.94, lon: 24.98 },
  plato: { name: 'Athens', lat: 37.98, lon: 23.73 },
  diogenes: { name: 'Sinope', lat: 42.03, lon: 35.15 },
  aristotle: { name: 'Stagira', lat: 40.53, lon: 23.75 },
  pyrrho: { name: 'Elis', lat: 37.89, lon: 21.37 },
  epicurus: { name: 'Samos', lat: 37.75, lon: 26.83 },
  zeno: { name: 'Citium', lat: 34.92, lon: 33.63 },
  marcus: { name: 'Rome', lat: 41.89, lon: 12.48 },
  plotinus: { name: 'Lycopolis', lat: 27.18, lon: 31.18 },
  augustine: { name: 'Thagaste', lat: 36.29, lon: 7.95 },
  anselm: { name: 'Aosta', lat: 45.74, lon: 7.32 },
  aquinas: { name: 'Roccasecca', lat: 41.55, lon: 13.67 },
  ockham: { name: 'Ockham, Surrey', lat: 51.3, lon: -0.45 },
  machiavelli: { name: 'Florence', lat: 43.77, lon: 11.25 },
  bacon: { name: 'London', lat: 51.51, lon: -0.13 },
  hobbes: { name: 'Malmesbury', lat: 51.58, lon: -2.1 },
  descartes: { name: 'La Haye, Touraine', lat: 46.99, lon: 0.7 },
  spinoza: { name: 'Amsterdam', lat: 52.37, lon: 4.9 },
  locke: { name: 'Wrington', lat: 51.36, lon: -2.76 },
  leibniz: { name: 'Leipzig', lat: 51.34, lon: 12.37 },
  berkeley: { name: 'Kilkenny', lat: 52.65, lon: -7.25 },
  hume: { name: 'Edinburgh', lat: 55.95, lon: -3.19 },
  rousseau: { name: 'Geneva', lat: 46.2, lon: 6.14 },
  kant: { name: 'Königsberg', lat: 54.71, lon: 20.51 },
  bentham: { name: 'London', lat: 51.51, lon: -0.13 },
  wollstonecraft: { name: 'London', lat: 51.52, lon: -0.07 },
  hegel: { name: 'Stuttgart', lat: 48.78, lon: 9.18 },
  schopenhauer: { name: 'Danzig', lat: 54.35, lon: 18.65 },
  mill: { name: 'London', lat: 51.53, lon: -0.11 },
  kierkegaard: { name: 'Copenhagen', lat: 55.68, lon: 12.57 },
  marx: { name: 'Trier', lat: 49.75, lon: 6.64 },
  james: { name: 'New York', lat: 40.71, lon: -74.01 },
  nietzsche: { name: 'Röcken', lat: 51.25, lon: 12.11 },
  russell: { name: 'Trellech, Wales', lat: 51.74, lon: -2.73 },
  wittgenstein: { name: 'Vienna', lat: 48.21, lon: 16.37 },
  heidegger: { name: 'Messkirch', lat: 47.99, lon: 9.11 },
  sartre: { name: 'Paris', lat: 48.86, lon: 2.35 },
  arendt: { name: 'Hanover', lat: 52.37, lon: 9.72 },
  beauvoir: { name: 'Paris', lat: 48.86, lon: 2.35 },
  camus: { name: 'Mondovi, Algeria', lat: 36.68, lon: 7.75 },
  rawls: { name: 'Baltimore', lat: 39.29, lon: -76.61 },
  foucault: { name: 'Poitiers', lat: 46.58, lon: 0.34 },
}

export const PHILOSOPHERS = WESTERN.map(p => ({
  ...p,
  ...DETAILS[p.id],
  tradition: 'western',
  portrait: `portraits/${p.id}.png`,
  place: PLACES[p.id],
  influenced: WESTERN.filter(q => q.influences.includes(p.id)).map(q => q.id),
}))

export const byId = Object.fromEntries(PHILOSOPHERS.map(p => [p.id, p]))
export const eraById = Object.fromEntries(ERAS.map(e => [e.id, e]))
