// One line on what actually passed along each influence edge, keyed 'from>to'.
// A test asserts every influences[] pair in the data has an entry here.
export const EDGES = {
  'thales>anaximander': 'His student and successor at Miletus — inherited the project of explaining nature without myth.',
  'socrates>plato': 'Teacher and martyr: the questioning method, and a death that made philosophy a calling.',
  'parmenides>plato': 'The problem of being versus becoming — the theory of Forms is Plato’s answer to Parmenides.',
  'pythagoras>plato': 'Mathematics as the soul’s ladder, and the soul’s immortality and transmigration.',
  'socrates>diogenes': 'Socratic self-mastery stripped of politeness and pushed to street theater.',
  'socrates>zeno': 'The model of virtue as the only true good, transmitted through the Cynics.',
  'diogenes>zeno': 'Zeno trained under the Cynics; Stoicism is Cynic ethics made teachable.',
  'plato>aristotle': 'Twenty years in the Academy — then the Forms pulled down from heaven into things.',
  'democritus>pyrrho': 'Atomism’s lesson that appearances deceive, turned into suspension of judgment.',
  'democritus>epicurus': 'Atoms and void adopted wholesale; the swerve added to rescue freedom.',
  'zeno>marcus': 'Stoic doctrine received as daily practice — the Meditations are its exercise book.',
  'plato>plotinus': 'Plato read as mystical system: the Forms become stages of the soul’s ascent.',
  'plato>augustine': 'The intelligible world above the senses, ready to be baptized.',
  'plotinus>augustine': 'The "books of the Platonists" that cleared his path to conversion.',
  'augustine>anselm': 'Faith seeking understanding — Anselm’s whole program is Augustinian.',
  'aristotle>aquinas': '"The Philosopher": logic, nature, and ethics systematized into Christian theology.',
  'augustine>aquinas': 'Grace and interiority, held in balance against Aristotle’s naturalism.',
  'aristotle>ockham': 'The logic kept and sharpened; the metaphysical furniture cut away.',
  'machiavelli>hobbes': 'Politics grounded in how people actually behave — fear before virtue.',
  'descartes>spinoza': 'The geometric method and substance metaphysics, radicalized into monism.',
  'descartes>locke': 'The "way of ideas" — mind knowing its own contents — minus the innate ones.',
  'descartes>leibniz': 'Rationalist method embraced; mind-body dualism rejected for harmony.',
  'spinoza>leibniz': 'The one-substance challenge that monads were built to answer.',
  'locke>berkeley': 'Empiricist premises accepted, then turned against matter itself.',
  'locke>hume': 'Ideas from experience, pushed until causation and self dissolve.',
  'berkeley>hume': 'The critique of abstract ideas, wielded with fewer theological comforts.',
  'hume>kant': 'The jolt that "interrupted my dogmatic slumber" — causality made the critical question.',
  'rousseau>kant': 'Taught him to honor ordinary human dignity; the one portrait on Kant’s wall.',
  'hume>bentham': 'Utility as the ground of morals, converted from sentiment into arithmetic.',
  'rousseau>wollstonecraft': 'Emile’s theory of female education — answered point by point in the Vindication.',
  'kant>hegel': 'The critical philosophy inherited, then set in motion through history.',
  'kant>schopenhauer': 'The thing-in-itself accepted — and named: it is Will.',
  'plato>schopenhauer': 'The Ideas return as timeless grades of the Will’s objectification.',
  'bentham>mill': 'Raised inside the felicific calculus; spent a life humanizing it.',
  'hegel>kierkegaard': 'The System as the enemy: existence cannot be a paragraph in a dialectic.',
  'hegel>marx': 'The dialectic kept, "turned right side up" — matter moves history, not spirit.',
  'hegel>beauvoir': 'The master–slave dialectic, read into the relation of man and woman.',
  'mill>james': 'Empiricism with a liberal temper — Pragmatism is dedicated to Mill’s memory.',
  'heraclitus>nietzsche': 'The philosopher of becoming, claimed as the only true ancestor.',
  'schopenhauer>nietzsche': '"Schopenhauer as educator" — the Will affirmed where the teacher renounced it.',
  'leibniz>russell': 'Russell’s book on Leibniz forged the logical tools of analytic philosophy.',
  'hume>russell': 'Empiricist skepticism, restated with modern logic.',
  'russell>wittgenstein': 'Mentor in logic — whose program the Tractatus completed and then buried.',
  'kierkegaard>heidegger': 'Anxiety, the crowd, and the single individual, secularized into Dasein.',
  'nietzsche>heidegger': 'Nihilism read as the destiny of Western metaphysics.',
  'kierkegaard>sartre': 'The leap and the single individual — existence precedes essence begins here.',
  'nietzsche>sartre': 'God’s death taken seriously: values must be made, not found.',
  'heidegger>sartre': 'Being and Time transposed into a philosophy of radical freedom.',
  'heidegger>arendt': 'Her teacher — his depth and his political failure both became her subjects.',
  'augustine>arendt': 'Her dissertation topic: love in Augustine; natality echoes his new beginnings.',
  'sartre>beauvoir': 'Lifelong partnership — existentialist freedom, which she made situated and social.',
  'kierkegaard>camus': 'The leap of faith studied — and refused as "philosophical suicide."',
  'nietzsche>camus': 'Revolt and affirmation without ressentiment; the yes said inside the absurd.',
  'kant>rawls': 'Autonomy and the kingdom of ends, rebuilt as a procedure — the veil of ignorance.',
  'mill>rawls': 'The liberty principle inherited; the utilitarian foundation refused.',
  'nietzsche>foucault': 'Genealogy: asking of every value and institution, what history produced this?',
  'marx>foucault': 'Power taken seriously — then found everywhere, not just in the economy.',
  'wittgenstein>searle': 'Meaning as use, carried from ordinary-language Oxford into a systematic theory of speech acts.',
  'leibniz>kripke': 'Possible worlds, coined in seventeenth-century theodicy, made into exact semantics for necessity.',
  'russell>kripke': 'The description theory of names — received as orthodoxy, dismantled in three lectures.',
  'wittgenstein>kripke': 'The rule-following passages, read into "Kripkenstein" — the boldest skeptical paradox of the century.',
}
