// One line on what actually passed along each influence edge, keyed 'from>to'.
// A test asserts every influences[] pair in the data has an entry here.
export const EDGES = {
  'thales>anaximander': 'His student and successor at Miletus — inherited the project of explaining nature without myth.',
  'socrates>plato': 'Teacher and martyr: the questioning method, and a death that made philosophy a calling.',
  'parmenides>plato': 'The problem of being versus becoming — the theory of Forms is Plato’s answer to Parmenides.',
  'pythagoras>plato': 'Mathematics as the soul’s ladder, and the soul’s immortality and transmigration.',
  'socrates>diogenes': 'Socratic self-mastery stripped of politeness and pushed to street theater.',
  'socrates>zeno': 'The model of virtue as the only true good, transmitted through the Cynics.',
  'diogenes>zeno': 'Zeno trained under the Cynics; Stoicism is Cynic ethics made teachable.',
  'plato>aristotle': 'Twenty years in the Academy — then the Forms pulled down from heaven into things.',
  'democritus>pyrrho': 'Atomism’s lesson that appearances deceive, turned into suspension of judgment.',
  'democritus>epicurus': 'Atoms and void adopted wholesale; the swerve added to rescue freedom.',
  'zeno>marcus': 'Stoic doctrine received as daily practice — the Meditations are its exercise book.',
  'plato>plotinus': 'Plato read as mystical system: the Forms become stages of the soul’s ascent.',
  'plato>augustine': 'The intelligible world above the senses, ready to be baptized.',
  'plotinus>augustine': 'The "books of the Platonists" that cleared his path to conversion.',
  'augustine>anselm': 'Faith seeking understanding — Anselm’s whole program is Augustinian.',
  'aristotle>aquinas': '"The Philosopher": logic, nature, and ethics systematized into Christian theology.',
  'augustine>aquinas': 'Grace and interiority, held in balance against Aristotle’s naturalism.',
  'aristotle>ockham': 'The logic kept and sharpened; the metaphysical furniture cut away.',
  'machiavelli>hobbes': 'Politics grounded in how people actually behave — fear before virtue.',
  'descartes>spinoza': 'The geometric method and substance metaphysics, radicalized into monism.',
  'descartes>locke': 'The "way of ideas" — mind knowing its own contents — minus the innate ones.',
  'descartes>leibniz': 'Rationalist method embraced; mind-body dualism rejected for harmony.',
  'spinoza>leibniz': 'The one-substance challenge that monads were built to answer.',
  'locke>berkeley': 'Empiricist premises accepted, then turned against matter itself.',
  'locke>hume': 'Ideas from experience, pushed until causation and self dissolve.',
  'berkeley>hume': 'The critique of abstract ideas, wielded with fewer theological comforts.',
  'hume>kant': 'The jolt that "interrupted my dogmatic slumber" — causality made the critical question.',
  'rousseau>kant': 'Taught him to honor ordinary human dignity; the one portrait on Kant’s wall.',
  'hume>bentham': 'Utility as the ground of morals, converted from sentiment into arithmetic.',
  'rousseau>wollstonecraft': 'Emile’s theory of female education — answered point by point in the Vindication.',
  'kant>hegel': 'The critical philosophy inherited, then set in motion through history.',
  'kant>schopenhauer': 'The thing-in-itself accepted — and named: it is Will.',
  'plato>schopenhauer': 'The Ideas return as timeless grades of the Will’s objectification.',
  'bentham>mill': 'Raised inside the felicific calculus; spent a life humanizing it.',
  'hegel>kierkegaard': 'The System as the enemy: existence cannot be a paragraph in a dialectic.',
  'hegel>marx': 'The dialectic kept, "turned right side up" — matter moves history, not spirit.',
  'hegel>beauvoir': 'The master–slave dialectic, read into the relation of man and woman.',
  'mill>james': 'Empiricism with a liberal temper — Pragmatism is dedicated to Mill’s memory.',
  'heraclitus>nietzsche': 'The philosopher of becoming, claimed as the only true ancestor.',
  'schopenhauer>nietzsche': '"Schopenhauer as educator" — the Will affirmed where the teacher renounced it.',
  'leibniz>russell': 'Russell’s book on Leibniz forged the logical tools of analytic philosophy.',
  'hume>russell': 'Empiricist skepticism, restated with modern logic.',
  'russell>wittgenstein': 'Mentor in logic — whose program the Tractatus completed and then buried.',
  'kierkegaard>heidegger': 'Anxiety, the crowd, and the single individual, secularized into Dasein.',
  'nietzsche>heidegger': 'Nihilism read as the destiny of Western metaphysics.',
  'kierkegaard>sartre': 'The leap and the single individual — existence precedes essence begins here.',
  'nietzsche>sartre': 'God’s death taken seriously: values must be made, not found.',
  'heidegger>sartre': 'Being and Time transposed into a philosophy of radical freedom.',
  'heidegger>arendt': 'Her teacher — his depth and his political failure both became her subjects.',
  'augustine>arendt': 'Her dissertation topic: love in Augustine; natality echoes his new beginnings.',
  'sartre>beauvoir': 'Lifelong partnership — existentialist freedom, which she made situated and social.',
  'kierkegaard>camus': 'The leap of faith studied — and refused as "philosophical suicide."',
  'nietzsche>camus': 'Revolt and affirmation without ressentiment; the yes said inside the absurd.',
  'kant>rawls': 'Autonomy and the kingdom of ends, rebuilt as a procedure — the veil of ignorance.',
  'mill>rawls': 'The liberty principle inherited; the utilitarian foundation refused.',
  'nietzsche>foucault': 'Genealogy: asking of every value and institution, what history produced this?',
  'marx>foucault': 'Power taken seriously — then found everywhere, not just in the economy.',
  'wittgenstein>searle': 'Meaning as use, carried from ordinary-language Oxford into a systematic theory of speech acts.',
  'leibniz>kripke': 'Possible worlds, coined in seventeenth-century theodicy, made into exact semantics for necessity.',
  'russell>kripke': 'The description theory of names — received as orthodoxy, dismantled in three lectures.',
  'wittgenstein>kripke': 'The rule-following passages, read into "Kripkenstein" — the boldest skeptical paradox of the century.',
  'confucius>mozi': 'Trained in the Confucian school — then turned its family-first ethics into the target of impartial care.',
  'confucius>mencius': 'The master’s vision of virtue, inherited through his grandson’s school and given a theory of human nature.',
  'confucius>xunzi': 'Ritual and cultivation received — and regrounded in artifice rather than innate goodness.',
  'mozi>mencius': 'Impartial care attacked as denying fathers — Mencius’s ethics of graded love is his answer to Mozi.',
  'mencius>xunzi': 'The claim that nature is good, met with its great rebuttal: nature is crooked and ritual straightens it.',
  'laozi>zhuangzi': 'The Dao and effortless action, retold in parables and jokes instead of aphorisms.',
  'confucius>zhuxi': 'The Analects placed at the center of the Four Books — the classical sage systematized into orthodoxy.',
  'mencius>zhuxi': 'Canonized as the tradition’s second sage; his good nature becomes principle itself.',
  'mencius>wangyangming': 'Innate moral sprouts radicalized into liangzhi — good knowing complete in every mind.',
  'zhuxi>wangyangming': 'The orthodoxy he studied, tested on bamboo for seven days, and overturned: principle is in the mind, not in things.',
  'buddha>nagarjuna': 'Dependent origination and the middle way, sharpened into a dialectic of emptiness.',
  'nagarjuna>shankara': 'Madhyamaka’s two truths and world-as-appearance — absorbed so deeply that rivals called Advaita crypto-Buddhist.',
  'shankara>ramanuja': 'Stark non-dualism received as the position to beat: the world rescued as the real body of God.',
  'buddha>schopenhauer': 'The diagnosis of craving and suffering, recognized across two millennia as his own pessimism’s elder.',
  'aristotle>alkindi': 'First of the Greeks carried into Arabic under his direction at the House of Wisdom.',
  'plotinus>alkindi': 'Emanation absorbed through the so-called Theology of Aristotle — Plotinus wearing Aristotle’s name.',
  'aristotle>alfarabi': 'Logic and metaphysics mastered so thoroughly that the tradition named him the Second Teacher.',
  'plato>alfarabi': 'The Republic’s philosopher-ruler, rebuilt for the age of prophetic religion.',
  'alkindi>alfarabi': 'The project of Greek wisdom in Arabic, inherited and made systematic.',
  'aristotle>avicenna': 'Read forty times, understood — by his own telling — only with Al-Farabi’s help, then rebuilt around existence.',
  'alfarabi>avicenna': 'The little treatise on the Metaphysics that unlocked Aristotle’s aims for him.',
  'avicenna>alghazali': 'The system mastered in order to be attacked: the Incoherence takes his necessities apart from inside.',
  'aristotle>averroes': 'A lifetime of commentaries — short, middle, and long — on nearly the whole corpus.',
  'avicenna>averroes': 'The Persian synthesis criticized for straying from Aristotle’s plain sense.',
  'alghazali>averroes': 'The Incoherence answered point by point in The Incoherence of the Incoherence.',
  'averroes>ibnkhaldun': 'The Maghreb’s rationalist inheritance — absorbed, then aimed at history instead of metaphysics.',
  'aristotle>maimonides': 'The master of "the philosophers," harmonized with Torah in the Guide.',
  'alfarabi>maimonides': 'His logic and political philosophy — Maimonides told his translator to trust Al-Farabi above all.',
  'avicenna>aquinas': 'Essence and existence, the Necessary Existent — the metaphysical vocabulary of the Summa arrived from Persia.',
  'averroes>aquinas': 'The Commentator: cited constantly, followed on method, fought fiercely on the unity of intellect.',
  'zeno>epictetus': 'Stoic doctrine received through the school’s living chain, and taught with a freed slave’s authority.',
  'epictetus>marcus': 'The Meditations thank a teacher for the loan of Epictetus’ notes — the slave instructing the emperor.',
  'plotinus>hypatia': 'The Neoplatonist curriculum of Alexandria — mathematics as the soul’s ladder toward the One.',
  'plato>boethius': 'Philosophy personified as the guide of souls — the Consolation is a prison Phaedo.',
  'aristotle>boethius': 'His logic, translated and transmitted — for centuries Europe’s only Aristotle was Boethius’ Latin.',
  'boethius>aquinas': 'The definition of eternity and the theological method — Aquinas wrote commentaries on his tractates.',
  'pyrrho>montaigne': 'Ancient skepticism rediscovered in print, weighed in the tower, and stamped on his medal: "Que sais-je?"',
  'montaigne>descartes': 'The skeptical crisis he made vivid — the doubt the Meditations were built to answer.',
  'montaigne>pascal': 'The great adversary kept closest at hand: the Pensées quarrel with him page by page.',
  'descartes>pascal': 'The geometric method admired, the God of the philosophers refused — "useless and uncertain."',
  'descartes>conway': 'Studied through Henry More’s Cartesian correspondence — then refuted: matter cannot be dead extension.',
  'conway>leibniz': 'Her Principles reached him via van Helmont; he said his views came near to hers — monads included.',
  'descartes>amo': 'The dualism he took apart with precision: sensing belongs to the living body, not the mind.',
  'kant>peirce': 'The Critique studied two hours a day for three years — categories reborn as a logic of signs.',
  'peirce>james': 'Pragmatism’s maxim, learned in their Metaphysical Club and made famous with due credit.',
  'leibniz>frege': 'The dream of a calculus of thought — the characteristica universalis — finally built.',
  'frege>russell': 'The logic Principia extended, and the system his paradox broke — announced in a letter of terrible politeness.',
  'frege>wittgenstein': 'Sense, reference, and the context principle — the Tractatus names him before Russell.',
  'descartes>husserl': 'The Meditations radicalized: the cogito becomes a field of investigation rather than a foundation stone.',
  'husserl>heidegger': 'Phenomenology’s method, inherited as assistant and heir — then turned from consciousness to Being.',
  'husserl>sartre': 'Intentionality discovered in a Berlin year — "he freed us from the inner life," Sartre said.',
  'buddha>dogen': 'The Dharma received through the Chan lineage and returned to its radical core: just sit.',
  'dogen>nishida': 'Zen practice as the ground of thought — being-time echoing through the logic of place.',
  'james>nishida': 'Pure experience, taken from James’s radical empiricism and made the first principle of a new philosophy.',
  'hume>popper': 'The problem of induction accepted as unanswerable — and sidestepped: science never induces, it conjectures.',
  'russell>quine': 'The logic and the ontology-by-paraphrase — "On What There Is" is Russell’s theory of descriptions at work.',
  'quine>kripke': 'Quine’s scorn for modality was the orthodoxy Naming and Necessity overturned.',
  'plato>weil': 'Read as a mystic: the Cave, the Good, and attention as the soul’s turning toward light.',
  'marx>weil': 'The oppression he diagnosed, tested in a factory year — and his theory found wanting on affliction.',
  'aristotle>anscombe': 'The virtues and practical reason, retrieved as the live alternative to modern moral law without a lawgiver.',
  'wittgenstein>anscombe': 'Teacher, friend, and testament: she translated the Investigations and guarded the method.',
}
